### ISSUE TITLE
[BUG] When running 'AUTO_SPEED' I get an error stating axises need to be homed

### ISSUE THREAD

**Issue by courtross2010** [Anonoei/klipper_auto_speed#28]
I installed the Klipper Auto Speed plugin on my Voron V2.4 and updated all the environments and packages.  When I run the 'AUTO_HOME' macro from the console, I get the error: 'Printer must be homed first! Found 2 homed axes.'

All of the axes have been homed.  This includes the ERCF MMU that I have on my printer.
![image](https://github.com/user-attachments/assets/c6d07eee-dc24-49ae-9298-19be9a519ecc)

**To Reproduce**
 1. Home all of the axes of the printer
 2. Open the console and type 'AUTO_HOME'
 3. Press Enter

**Printer (please complete the following information):**
 - Voron V2.4
 - Kinematics: CoreXY
 - Klipper Version: v0.12.0-286-g81de9a86
 - klippy.log attached: [klippy.log](https://github.com/user-attachments/files/16738138/klippy.log)
 - Klipper Auto Speed Version: v0.3.4-0-ga5ee2fb7

**Comment by ItsAzuur** [comment]
Same issue here on my Delta. All axis are homed but the macro tells me 0 axis are homed. Other macros needing home works no issue.

**Comment by theimmortal68** [comment]
I am also experiencing this issue. I have an Extended CoreXY configuration (https://github.com/SnakeOilXY/klipper-extended-corexy-kinematic) and it is telling me there are zero axis homed.

**Comment by izGHLooL** [comment]
> I installed the Klipper Auto Speed plugin on my Voron V2.4 and updated all the environments and packages. When I run the 'AUTO_HOME' macro from the console, I get the error: 'Printer must be homed first! Found 2 homed axes.' This particular error shows regardless of the currently homed axes. None can be homed, and you will receive the same error.
> 
> All of the axes have been homed. This includes the ERCF MMU that I have on my printer. ![image](https://github.com/user-attachments/assets/c6d07eee-dc24-49ae-9298-19be9a519ecc)
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Home all of the axes of the printer
> 2. Open the console and type 'AUTO_HOME'
> 3. Press Enter
> 
> **Printer (please complete the following information):**
> 
> * Voron V2.4
> * Kinematics: CoreXY
> * Klipper Version: v0.12.0-286-g81de9a86
> * klippy.log attached: [klippy.log](https://github.com/user-attachments/files/16738138/klippy.log)
> * Klipper Auto Speed Version: v0.3.4-0-ga5ee2fb7

I had the same issue and i got it working by homing all axis and the perform Beacon touch / cartographer touch , that triggered the z homing flag in klipper resulting in making auto speed to work

**Comment by Matze0811** [comment]
I have exactly the same Error. No matter if 1 or 2 or 3 or even no axis is homed, i got ther error "Printer must be homed first! Found 2 homed axes."

**Comment by izGHLooL** [comment]
> I have exactly the same Error. No matter if 1 or 2 or 3 or even no axis is homed, i got ther error "Printer must be homed first! Found 2 homed axes."

do you use virtual z endstop ? if so you have to perform beacon\cartographer touch after you home all axis this will insure that klipper flag z as homed and then you can do the speed tune macro with no problem

**Comment by Matze0811** [comment]
> > I have exactly the same Error. No matter if 1 or 2 or 3 or even no axis is homed, i got ther error "Printer must be homed first! Found 2 homed axes."
> 
> do you use virtual z endstop ? if so you have to perform beacon\cartographer touch after you home all axis this will insure that klipper flag z as homed and then you can do the speed tune macro with no problem

I do use virtual z endstop. My Endstop is my BLTouch. There's nothing to touch on it cause pin is already retracted. The weird is, it has worked!
I've updated my klipper installation from time to time, one day autospeed stopped to work and dropped the error. I can't say which klipper version has done this, cause i don't use autospeed often.

**Comment by danny83germany** [comment]
I made me a workaround:

First a new file homing_patch.py in the klippy/extras

```
from . import homing


_original_do_home_z_via_probe = homing.Homing._do_home_z_via_probe


def patched_do_home_z_via_probe(self, rails, forcepos, movepos):
    self.printer.send_event(
        "homing:home_rails_begin", self, rails)

    result = _original_do_home_z_via_probe(
        self, rails, forcepos, movepos)

    self.printer.send_event(
        "homing:home_rails_end", self, rails)

    return result


class HomingPatch:
    def __init__(self, config):
        self.printer = config.get_printer()

        homing.Homing._do_home_z_via_probe = (
            patched_do_home_z_via_probe
        )


def load_config(config):
    return HomingPatch(config)
```

in the printer.cfg add 
`[homing_patch]`

I hope this helps for the momemt and let me know your experience.

**Comment by Matze0811** [comment]
> I made me a workaround:
> 
> First a new file homing_patch.py in the klippy/extras
> 
> ```
> from . import homing
> 
> 
> _original_do_home_z_via_probe = homing.Homing._do_home_z_via_probe
> 
> 
> def patched_do_home_z_via_probe(self, rails, forcepos, movepos):
>     self.printer.send_event(
>         "homing:home_rails_begin", self, rails)
> 
>     result = _original_do_home_z_via_probe(
>         self, rails, forcepos, movepos)
> 
>     self.printer.send_event(
>         "homing:home_rails_end", self, rails)
> 
>     return result
> 
> 
> class HomingPatch:
>     def __init__(self, config):
>         self.printer = config.get_printer()
> 
>         homing.Homing._do_home_z_via_probe = (
>             patched_do_home_z_via_probe
>         )
> 
> 
> def load_config(config):
>     return HomingPatch(config)
> ```
> 
> in the printer.cfg add `[homing_patch]`
> 
> I hope this helps for the momemt and let me know your experience.

Sadly, it doesnt work for me
"Internal error on command:"G28.6245197"
Once the underlying issue is corrected, use the
"FIRMWARE_RESTART" command to reset the firmware, reload the
config, and restart the host software.
Printer is shutdown"

"Internal error on command:"G28.6245197"
Internal error on command:"_LAZY_HOME_INNER"
Traceback (most recent call last):
  File "/home/mks/klipper/klippy/gcode.py", line 223, in _process_commands
    handler(gcmd)
    ~~~~~~~^^^^^^
  File "/home/mks/klipper/klippy/gcode.py", line 151, in <lambda>
    func = lambda params: origfunc(self._get_extended_params(params))
                          ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mks/klipper/klippy/extras/gcode_macro.py", line 198, in cmd
    self.template.run_gcode_from_command(kwparams)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/home/mks/klipper/klippy/extras/gcode_macro.py", line 77, in run_gcode_from_command
    self.gcode.run_script_from_command(self.render(context))
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mks/klipper/klippy/gcode.py", line 238, in run_script_from_command
    self._process_commands(script.split('\n'), need_ack=False)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mks/klipper/klippy/gcode.py", line 223, in _process_commands
    handler(gcmd)
    ~~~~~~~^^^^^^
  File "/home/mks/klipper/klippy/extras/safe_z_home.py", line 81, in cmd_G28
    self.prev_G28(g28_gcmd)
    ~~~~~~~~~~~~~^^^^^^^^^^
  File "/home/mks/klipper/klippy/extras/homing.py", line 349, in cmd_G28
    kin.home(homing_state)
    ~~~~~~~~^^^^^^^^^^^^^^
  File "/home/mks/klipper/klippy/kinematics/cartesian.py", line 96, in home
    self.home_axis(homing_state, axis, self.rails[axis])
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mks/klipper/klippy/kinematics/cartesian.py", line 89, in home_axis
    homing_state.home_rails([rail], forcepos, homepos)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mks/klipper/klippy/extras/homing.py", line 293, in home_rails
    self._do_home_z_via_probe(rails, forcepos, movepos)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mks/klipper/klippy/extras/homing_patch.py", line 14, in patched_do_home_z_via_probe
    self.printer.send_event(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        "homing:home_rails_end", self, rails)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mks/klipper/klippy/klippy.py", line 227, in send_event
    return [cb(*params) for cb in self.event_handlers.get(event, [])]
            ~~^^^^^^^^^
  File "/home/mks/klipper/klippy/extras/endstop_phase.py", line 121, in handle_home_rails_end
    stepper = rail.get_endstops()[0][0].get_steppers()[0]
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
Internal error on command:"_LAZY_HOME_INNER"
Internal error on command:"LAZY_HOME"
Traceback (most recent call last):
  File "/home/mks/klipper/klippy/gcode.py", line 223, in _process_commands
    handler(gcmd)
    ~~~~~~~^^^^^^
  File "/home/mks/klipper/klippy/gcode.py", line 151, in <lambda>
    func = lambda params: origfunc(self._get_extended_params(params))
                          ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mks/klipper/klippy/extras/gcode_macro.py", line 198, in cmd
    self.template.run_gcode_from_command(kwparams)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/home/mks/klipper/klippy/extras/gcode_macro.py", line 77, in run_gcode_from_command
    self.gcode.run_script_from_command(self.render(context))
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mks/klipper/klippy/gcode.py", line 238, in run_script_from_command
    self._process_commands(script.split('\n'), need_ack=False)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mks/klipper/klippy/gcode.py", line 223, in _process_commands
    handler(gcmd)
    ~~~~~~~^^^^^^
  File "/home/mks/klipper/klippy/gcode.py", line 151, in <lambda>
    func = lambda params: origfunc(self._get_extended_params(params))
                          ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mks/klipper/klippy/extras/gcode_macro.py", line 198, in cmd
    self.template.run_gcode_from_command(kwparams)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/home/mks/klipper/klippy/extras/gcode_macro.py", line 77, in run_gcode_from_command
    self.gcode.run_script_from_command(self.render(context))
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mks/klipper/klippy/gcode.py", line 238, in run_script_from_command
    self._process_commands(script.split('\n'), need_ack=False)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mks/klipper/klippy/gcode.py", line 223, in _process_commands
    handler(gcmd)
    ~~~~~~~^^^^^^
  File "/home/mks/klipper/klippy/extras/safe_z_home.py", line 81, in cmd_G28
    self.prev_G28(g28_gcmd)
    ~~~~~~~~~~~~~^^^^^^^^^^
  File "/home/mks/klipper/klippy/extras/homing.py", line 349, in cmd_G28
    kin.home(homing_state)
    ~~~~~~~~^^^^^^^^^^^^^^
  File "/home/mks/klipper/klippy/kinematics/cartesian.py", line 96, in home
    self.home_axis(homing_state, axis, self.rails[axis])
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mks/klipper/klippy/kinematics/cartesian.py", line 89, in home_axis
    homing_state.home_rails([rail], forcepos, homepos)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mks/klipper/klippy/extras/homing.py", line 293, in home_rails
    self._do_home_z_via_probe(rails, forcepos, movepos)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mks/klipper/klippy/extras/homing_patch.py", line 14, in patched_do_home_z_via_probe
    self.printer.send_event(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        "homing:home_rails_end", self, rails)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mks/klipper/klippy/klippy.py", line 227, in send_event
    return [cb(*params) for cb in self.event_handlers.get(event, [])]
            ~~^^^^^^^^^
  File "/home/mks/klipper/klippy/extras/endstop_phase.py", line 121, in handle_home_rails_end
    stepper = rail.get_endstops()[0][0].get_steppers()[0]
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
Internal error on command:"LAZY_HOME"
Internal error on command:"G28"
Traceback (most recent call last):
  File "/home/mks/klipper/klippy/gcode.py", line 223, in _process_commands
    handler(gcmd)
    ~~~~~~~^^^^^^
  File "/home/mks/klipper/klippy/extras/gcode_macro.py", line 198, in cmd
    self.template.run_gcode_from_command(kwparams)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/home/mks/klipper/klippy/extras/gcode_macro.py", line 77, in run_gcode_from_command
    self.gcode.run_script_from_command(self.render(context))
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mks/klipper/klippy/gcode.py", line 238, in run_script_from_command
    self._process_commands(script.split('\n'), need_ack=False)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mks/klipper/klippy/gcode.py", line 223, in _process_commands
    handler(gcmd)
    ~~~~~~~^^^^^^
  File "/home/mks/klipper/klippy/gcode.py", line 151, in <lambda>
    func = lambda params: origfunc(self._get_extended_params(params))
                          ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mks/klipper/klippy/extras/gcode_macro.py", line 198, in cmd
    self.template.run_gcode_from_command(kwparams)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/home/mks/klipper/klippy/extras/gcode_macro.py", line 77, in run_gcode_from_command
    self.gcode.run_script_from_command(self.render(context))
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mks/klipper/klippy/gcode.py", line 238, in run_script_from_command
    self._process_commands(script.split('\n'), need_ack=False)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mks/klipper/klippy/gcode.py", line 223, in _process_commands
    handler(gcmd)
    ~~~~~~~^^^^^^
  File "/home/mks/klipper/klippy/gcode.py", line 151, in <lambda>
    func = lambda params: origfunc(self._get_extended_params(params))
                          ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mks/klipper/klippy/extras/gcode_macro.py", line 198, in cmd
    self.template.run_gcode_from_command(kwparams)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/home/mks/klipper/klippy/extras/gcode_macro.py", line 77, in run_gcode_from_command
    self.gcode.run_script_from_command(self.render(context))
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mks/klipper/klippy/gcode.py", line 238, in run_script_from_command
    self._process_commands(script.split('\n'), need_ack=False)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mks/klipper/klippy/gcode.py", line 223, in _process_commands
    handler(gcmd)
    ~~~~~~~^^^^^^
  File "/home/mks/klipper/klippy/extras/safe_z_home.py", line 81, in cmd_G28
    self.prev_G28(g28_gcmd)
    ~~~~~~~~~~~~~^^^^^^^^^^
  File "/home/mks/klipper/klippy/extras/homing.py", line 349, in cmd_G28
    kin.home(homing_state)
    ~~~~~~~~^^^^^^^^^^^^^^
  File "/home/mks/klipper/klippy/kinematics/cartesian.py", line 96, in home
    self.home_axis(homing_state, axis, self.rails[axis])
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mks/klipper/klippy/kinematics/cartesian.py", line 89, in home_axis
    homing_state.home_rails([rail], forcepos, homepos)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mks/klipper/klippy/extras/homing.py", line 293, in home_rails
    self._do_home_z_via_probe(rails, forcepos, movepos)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mks/klipper/klippy/extras/homing_patch.py", line 14, in patched_do_home_z_via_probe
    self.printer.send_event(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        "homing:home_rails_end", self, rails)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mks/klipper/klippy/klippy.py", line 227, in send_event
    return [cb(*params) for cb in self.event_handlers.get(event, [])]
            ~~^^^^^^^^^
  File "/home/mks/klipper/klippy/extras/endstop_phase.py", line 121, in handle_home_rails_end
    stepper = rail.get_endstops()[0][0].get_steppers()[0]
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
Internal error on command:"G28"
Internal Error on WebRequest: gcode/script
Traceback (most recent call last):
  File "/home/mks/klipper/klippy/webhooks.py", line 268, in _process_request
    func(web_request)
    ~~~~^^^^^^^^^^^^^
  File "/home/mks/klipper/klippy/webhooks.py", line 448, in _handle_script
    self.gcode.run_script(web_request.get_str('script'))
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mks/klipper/klippy/gcode.py", line 241, in run_script
    self._process_commands(script.split('\n'), need_ack=False)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mks/klipper/klippy/gcode.py", line 223, in _process_commands
    handler(gcmd)
    ~~~~~~~^^^^^^
  File "/home/mks/klipper/klippy/extras/gcode_macro.py", line 198, in cmd
    self.template.run_gcode_from_command(kwparams)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/home/mks/klipper/klippy/extras/gcode_macro.py", line 77, in run_gcode_from_command
    self.gcode.run_script_from_command(self.render(context))
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mks/klipper/klippy/gcode.py", line 238, in run_script_from_command
    self._process_commands(script.split('\n'), need_ack=False)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mks/klipper/klippy/gcode.py", line 223, in _process_commands
    handler(gcmd)
    ~~~~~~~^^^^^^
  File "/home/mks/klipper/klippy/gcode.py", line 151, in <lambda>
    func = lambda params: origfunc(self._get_extended_params(params))
                          ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mks/klipper/klippy/extras/gcode_macro.py", line 198, in cmd
    self.template.run_gcode_from_command(kwparams)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/home/mks/klipper/klippy/extras/gcode_macro.py", line 77, in run_gcode_from_command
    self.gcode.run_script_from_command(self.render(context))
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mks/klipper/klippy/gcode.py", line 238, in run_script_from_command
    self._process_commands(script.split('\n'), need_ack=False)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mks/klipper/klippy/gcode.py", line 223, in _process_commands
    handler(gcmd)
    ~~~~~~~^^^^^^
  File "/home/mks/klipper/klippy/gcode.py", line 151, in <lambda>
    func = lambda params: origfunc(self._get_extended_params(params))
                          ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mks/klipper/klippy/extras/gcode_macro.py", line 198, in cmd
    self.template.run_gcode_from_command(kwparams)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/home/mks/klipper/klippy/extras/gcode_macro.py", line 77, in run_gcode_from_command
    self.gcode.run_script_from_command(self.render(context))
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mks/klipper/klippy/gcode.py", line 238, in run_script_from_command
    self._process_commands(script.split('\n'), need_ack=False)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mks/klipper/klippy/gcode.py", line 223, in _process_commands
    handler(gcmd)
    ~~~~~~~^^^^^^
  File "/home/mks/klipper/klippy/extras/safe_z_home.py", line 81, in cmd_G28
    self.prev_G28(g28_gcmd)
    ~~~~~~~~~~~~~^^^^^^^^^^
  File "/home/mks/klipper/klippy/extras/homing.py", line 349, in cmd_G28
    kin.home(homing_state)
    ~~~~~~~~^^^^^^^^^^^^^^
  File "/home/mks/klipper/klippy/kinematics/cartesian.py", line 96, in home
    self.home_axis(homing_state, axis, self.rails[axis])
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mks/klipper/klippy/kinematics/cartesian.py", line 89, in home_axis
    homing_state.home_rails([rail], forcepos, homepos)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mks/klipper/klippy/extras/homing.py", line 293, in home_rails
    self._do_home_z_via_probe(rails, forcepos, movepos)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mks/klipper/klippy/extras/homing_patch.py", line 14, in patched_do_home_z_via_probe
    self.printer.send_event(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        "homing:home_rails_end", self, rails)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mks/klipper/klippy/klippy.py", line 227, in send_event
    return [cb(*params) for cb in self.event_handlers.get(event, [])]
            ~~^^^^^^^^^
  File "/home/mks/klipper/klippy/extras/endstop_phase.py", line 121, in handle_home_rails_end
    stepper = rail.get_endstops()[0][0].get_steppers()[0]
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
"
Is the complete Error-Log

**Comment by danny83germany** [comment]
@Matze0811 

For AUTO_SPEED, the following sections need to be temporarily disabled:

```
[endstop_phase stepper_x]
[endstop_phase stepper_y]
[endstop_phase stepper_z]
```

After that, you can disable `[auto_speed]` again and re-enable the endstop_phase sections.

This is only required temporarily for the AUTO_SPEED test.

This should solve it for you to.

**Comment by danny83germany** [comment]
Alternative is to change the main.py of AUTO_SPEED

Comment
` #    self.printer.register_event_handler("homing:home_rails_end", self.handle_home_rails_end)`

Change handle_connect
```
  def handle_connect(self):
        self.toolhead = self.printer.lookup_object('toolhead')
        # Reduce speed/acceleration for positioning movement
        self.th_accel = self.toolhead.max_accel/2
        self.th_veloc = self.toolhead.max_velocity/2
        self.th_scv = self.toolhead.square_corner_velocity

        # Find and define leveling method
        if self.printer.lookup_object("screw_tilt_adjust", None) is not None:
            self.level = "STA"
        elif self.printer.lookup_object("z_tilt", None) is not None:
            self.level= "ZT"
        elif self.printer.lookup_object("quad_gantry_level", None) is not None:
            self.level = "QGL"
        else:
            self.level = None

        rails = self.printer.lookup_object("toolhead").get_kinematics().rails
      
        if not len(self.steppers.keys()) == 3:
                    for rail in rails:
                        pos_min, pos_max = rail.get_range()
                        for stepper in rail.get_steppers():
                            name = stepper._name
                            # microsteps = (stepper._steps_per_rotation / full_steps / gearing)
                            if name in ["stepper_x", "stepper_y", "stepper_z"]:
                                config = self.printer.lookup_object('configfile').status_raw_config[name]
                                microsteps = int(config["microsteps"])
        
                                homing_retract_dist = config.get("homing_retract_dist", None)
                                if homing_retract_dist is None:
                                    homing_retract_dist = 5 # This shouldn't be hardcoded
                                homing_retract_dist = float(homing_retract_dist)
                                second_homing_speed = config.get("second_homing_speed", None)
                                if second_homing_speed is None:
                                    second_homing_speed = 5 # This shouldn't be hardcoded
                                second_homing_speed = float(second_homing_speed)
                                self.steppers[name[-1]] = [pos_min, pos_max, microsteps, homing_retract_dist, second_homing_speed]
        
                    if self.steppers.get("x", None) is not None:
                        self.axis_limits["x"] = {
                            "min": self.steppers["x"][0],
                            "max": self.steppers["x"][1],
                            "center": (self.steppers["x"][0] + self.steppers["x"][1]) / 2,
                            "dist": self.steppers["x"][1] - self.steppers["x"][0],
                            "home": self.gcode_move.homing_position[0]
                        }
                    if self.steppers.get("y", None) is not None:
                        self.axis_limits["y"] = {
                            "min": self.steppers["y"][0],
                            "max": self.steppers["y"][1],
                            "center": (self.steppers["y"][0] + self.steppers["y"][1]) / 2,
                            "dist": self.steppers["y"][1] - self.steppers["y"][0],
                            "home": self.gcode_move.homing_position[1]
                        }
                    if self.steppers.get("z", None) is not None:
                        self.axis_limits["z"] = {
                            "min": self.steppers["z"][0],
                            "max": self.steppers["z"][1],
                            "center": (self.steppers["z"][0] + self.steppers["z"][1]) / 2,
                            "dist": self.steppers["z"][1] - self.steppers["z"][0],
                            "home": self.gcode_move.homing_position[2]
                        }
```
  
And Comment the complete block of ( before and after """)

`def handle_home_rails_end(self, homing_state, rails):`


Is not tested completly

**Comment by Matze0811** [comment]
> Alternative is to change the main.py of AUTO_SPEED
> 
> Comment ` # self.printer.register_event_handler("homing:home_rails_end", self.handle_home_rails_end)`
> 
> Change handle_connect
> 
> ```
>   def handle_connect(self):
>         self.toolhead = self.printer.lookup_object('toolhead')
>         # Reduce speed/acceleration for positioning movement
>         self.th_accel = self.toolhead.max_accel/2
>         self.th_veloc = self.toolhead.max_velocity/2
>         self.th_scv = self.toolhead.square_corner_velocity
> 
>         # Find and define leveling method
>         if self.printer.lookup_object("screw_tilt_adjust", None) is not None:
>             self.level = "STA"
>         elif self.printer.lookup_object("z_tilt", None) is not None:
>             self.level= "ZT"
>         elif self.printer.lookup_object("quad_gantry_level", None) is not None:
>             self.level = "QGL"
>         else:
>             self.level = None
> 
>         rails = self.printer.lookup_object("toolhead").get_kinematics().rails
>       
>         if not len(self.steppers.keys()) == 3:
>                     for rail in rails:
>                         pos_min, pos_max = rail.get_range()
>                         for stepper in rail.get_steppers():
>                             name = stepper._name
>                             # microsteps = (stepper._steps_per_rotation / full_steps / gearing)
>                             if name in ["stepper_x", "stepper_y", "stepper_z"]:
>                                 config = self.printer.lookup_object('configfile').status_raw_config[name]
>                                 microsteps = int(config["microsteps"])
>         
>                                 homing_retract_dist = config.get("homing_retract_dist", None)
>                                 if homing_retract_dist is None:
>                                     homing_retract_dist = 5 # This shouldn't be hardcoded
>                                 homing_retract_dist = float(homing_retract_dist)
>                                 second_homing_speed = config.get("second_homing_speed", None)
>                                 if second_homing_speed is None:
>                                     second_homing_speed = 5 # This shouldn't be hardcoded
>                                 second_homing_speed = float(second_homing_speed)
>                                 self.steppers[name[-1]] = [pos_min, pos_max, microsteps, homing_retract_dist, second_homing_speed]
>         
>                     if self.steppers.get("x", None) is not None:
>                         self.axis_limits["x"] = {
>                             "min": self.steppers["x"][0],
>                             "max": self.steppers["x"][1],
>                             "center": (self.steppers["x"][0] + self.steppers["x"][1]) / 2,
>                             "dist": self.steppers["x"][1] - self.steppers["x"][0],
>                             "home": self.gcode_move.homing_position[0]
>                         }
>                     if self.steppers.get("y", None) is not None:
>                         self.axis_limits["y"] = {
>                             "min": self.steppers["y"][0],
>                             "max": self.steppers["y"][1],
>                             "center": (self.steppers["y"][0] + self.steppers["y"][1]) / 2,
>                             "dist": self.steppers["y"][1] - self.steppers["y"][0],
>                             "home": self.gcode_move.homing_position[1]
>                         }
>                     if self.steppers.get("z", None) is not None:
>                         self.axis_limits["z"] = {
>                             "min": self.steppers["z"][0],
>                             "max": self.steppers["z"][1],
>                             "center": (self.steppers["z"][0] + self.steppers["z"][1]) / 2,
>                             "dist": self.steppers["z"][1] - self.steppers["z"][0],
>                             "home": self.gcode_move.homing_position[2]
>                         }
> ```
> 
> And Comment the complete block of ( before and after """)
> 
> `def handle_home_rails_end(self, homing_state, rails):`
> 
> Is not tested completly



> [@Matze0811](https://github.com/Matze0811)
> 
> For AUTO_SPEED, the following sections need to be temporarily disabled:
> 
> ```
> [endstop_phase stepper_x]
> [endstop_phase stepper_y]
> [endstop_phase stepper_z]
> ```
> 
> After that, you can disable `[auto_speed]` again and re-enable the endstop_phase sections.
> 
> This is only required temporarily for the AUTO_SPEED test.
> 
> This should solve it for you to.

You are great!!!
Disabling the endstop phases already does the trick!

Thank you very much for it!

**Comment by cmarchand0002** [comment]
This may be a silly question, but where do i go to disable to endstop phases?

**Comment by Matze0811** [comment]
> This may be a silly question, but where do i go to disable to endstop phases?

Put in in your printer.cfg
